language: ruby
rvm:
- 2.3.5
addons:
    code_climate:
        repo_token: TsGEMw9wWbDRQfiWhcVeR5HtDJEn/d6AEFZut+BBzJrm4904NBo+ltUL5OyC/B65LdLi9U9EI7LLB2MOfdn1GxJvIdymm/f5D8hPinEJfRNPQvqogzG8pUfMolrL4XV1arptVSDKNoj3W82ccgcBakV/ocVz/Uyx4Mt+BXnRWYiAcZF8TFvr5qik1KHg1UDXb1L63xa4I10KHwBwv9wwPorIPLhT0k8L9Vhp8632y2wVkNfeHy1W4ry5VIeAQd7w6+9t5Rqbgf9V0M/qImvtOCU2CzOMyMK1KX13M5ctk23cgmvCCP2qIsnxn/2OE2mSfbedTUSdTaDTDk5GfMz3Hw+rg+vAQmo0vm2O36VmjZTRyP9ytUbqb/1yHrNfmFRnFGnwbcCDzmve03PxRQaBdWBMeAgQYzNmy1178OQD7BxE0M2o1PYC7y/Cb9RP5GbzIbMSxgchbdiyyC64bM+YwYiId/71YZ0GQxLFxuL8Hx5b0QhhpnR/luG969nTcLqnXd8NFMa1ryQ43KJ10I7LPIpqDmbrWOLtVsVtrCCxh4HtlHRe0JYbLle0mqXu8NNk80Y3dkE+gMePLd40wBZiy5Rq86M6fbbyEFZESC2WSo0xtjMjJWM91no8vCRR5EnGDrMN/uJ3+AaZ6P5FaM77RMaSaWuDrZkybSsRnZsA5OI=
deploy:
  provider: heroku
  api_key:
    secure: siGOCHWj3fXmVH+NkPPjSaQGUoVDM0gwRszfqQzr/Kn5Fk2uIJjAVJXTRBg2sfDbF57jBdY+EkirvbClIvbW1atv/zP4sNGUBG5uCM/XZEPz1azbYjRZMVBxMz3f9Niho+s44ECdWiY0xEUyxs+ePQpXSYSgO9tvOGGAzQVPzfder+O9r7g7j3J6uw3RwozJyjHEgnD6jPIMka2FQvZHPzFET4R3Wb7quIJqMKHa8g8pDYpTYM7d2YNvWCjv5sXEAuRoHrRRMKICL6Kb8onpreivXv2WAjYkMV+6CUSmBDTmAUMOjOwqOU8uSOKPC/5OXcDllTypTx8zzDo3JXDMC9EYqKm4qbrAI1h378MuUipcwxNykQmPZ3sdseqFOOcmT9uuWuQieADfMYLbo3qrVqXMcjO1BUXl26RoYtzXww+rOTzLHgRucCfg0JnJJ6KNuuGcCVV5S5xXfJaQe3ofVw43MrSpmg44Lto4XJ+s4CWG0KVwB6ZVKUBmYKYUT6RGYQJ/Gerh07jwzaFmjSkHwdMfKTlpCNRt9EPo+R6sUHYL5lJavRO61QTVNWoR3Vr80PBK2bpXZsmjcXFtjfqLXyXFnjrvAI/pnY2BXtgO/yE2cCEaDuBCaSw823joIZLdQoJJdTaUxLrOkrX+Xyww7SxlUcA8RFuRk5BjYBHPSWU=
  app: projetlpa2111
  on:
    repo: yaman0/projet_LPA2
  run: "rake db:migrate"
before_script:
  - psql -c 'create database db_test;' -U postgres
