language: ruby
rvm:
- 2.3.5
env:
  global:
  - secure: k2OyaD6lVCormc9gTTROhhCHwAgiwRmxHjUexqCYEZI11uaRVY9CA0xzpYq6elxZ9uRtykZ+nb4arZQcai+A6BMtZ6HCdLa5LvvgCRKU0VB+l5xB2NGtX/NBNYbr+16NENZx07yRNLo8MMFk280WdBkr1/FjFJF9GX8/SMdIt/EWwh5CqxpnVwVk3kG06C6v62SG7u3qh/op38Zs3ns7F4tHuVA+qTMNMchW+5lb9lc8olNJVtHn+ilwTE84gIx91rfSSy6yzbEwZ8AVrrPAWzAtqgu+IS/o+EoG2/D1Hw4mEF9nTdwfkOnn8eCjESoQ/MzCRhiSeK/7kYHiPKnyL/d2/Hd7JEEz9AC8RXSUpFskUU/7UcvBhdO7wQ1ZO83AlyqW2POXV4QhXd2izgU2zIwTUVrQpUkAdGQYSArS2gOEYVHl2HaXPaGIksIRCoDZvcJYYhXroiUuNvXmScZZ/2BYlzO4bzxzH/Uw7t8OfSfDuf7J/tjFROXpVnN96Mk12X8DUxdiMhWF6VI9bmWTjB+ZyB/j9w6kc1SOCAXvgaHRkUJhV01QAdzD5tUT4033aWcBH0CpVp8y2WzssUG1gt1EdXHNJIQp9snkrecKP5P0N04sdJfvm7pGIN88x76nYdKjJ3NU8fZlsATtZB+6FGdFLjSB9X6cEAR93eIcYmU=
  - secure: XlhV7SzGK6VKaxoztT4puZ0qykU05wNpgYQoLQIxFc2zm9ERhH2HgtOlZEhiS5MJI426mG285BrvMc/PIwuzuvkwMIyGZqlgY3jv9VuUc0ZsfR0HiFilSuWuH1giG0kG56/GzpVHPNiXVgyO997BE5YKoEyNVzzZtnOvZCx7n96we07217Eek1ezmcb8XZyCr+Rd0NwzM4K/1FqatfHtblsWlZPizFtrQWOC5/CdN55ID+2CAOxDE+lyc07aIYrzZ4svX+EAtSHARq1C5+kpKXAAn+H6pSKoSXEd74EuB2V/dawedoje552mii+ffYEAvGV9vjkVnjfSrJcR8X36lUG5MDaYTF8it3T/VFiwT/PYPAeqOOcivuDW+v1IlnougK+h5q3JIbhVCLMCM54WZJEFIOfrqGFy9Ds8EMVJgHMC1kt9tfkiSm9iyiDknlp2mZ7Wg2MEQXmoLWPE+HQIXUo51IEMy939pmf+q3qHYUOmLTgE1j8lPCVAJRUSnxyTpklihxx2u4D7u639uZyUizgrZRCF23nbKupO/BjwQcO9mx6q/4XtuhbCLtGbAn1vTp0hoyd6ZWZxZRaeaTmCeHMsZdGlA5SxiCE1Or+q3ckAw2xAp01wxD6UFwZWsFAMf0G2hEyvUUYAPuKWrh9HdYvpNPpvvGNTRSWZWEWYVaI=
deploy:
  provider: heroku
  api_key:
    secure: siGOCHWj3fXmVH+NkPPjSaQGUoVDM0gwRszfqQzr/Kn5Fk2uIJjAVJXTRBg2sfDbF57jBdY+EkirvbClIvbW1atv/zP4sNGUBG5uCM/XZEPz1azbYjRZMVBxMz3f9Niho+s44ECdWiY0xEUyxs+ePQpXSYSgO9tvOGGAzQVPzfder+O9r7g7j3J6uw3RwozJyjHEgnD6jPIMka2FQvZHPzFET4R3Wb7quIJqMKHa8g8pDYpTYM7d2YNvWCjv5sXEAuRoHrRRMKICL6Kb8onpreivXv2WAjYkMV+6CUSmBDTmAUMOjOwqOU8uSOKPC/5OXcDllTypTx8zzDo3JXDMC9EYqKm4qbrAI1h378MuUipcwxNykQmPZ3sdseqFOOcmT9uuWuQieADfMYLbo3qrVqXMcjO1BUXl26RoYtzXww+rOTzLHgRucCfg0JnJJ6KNuuGcCVV5S5xXfJaQe3ofVw43MrSpmg44Lto4XJ+s4CWG0KVwB6ZVKUBmYKYUT6RGYQJ/Gerh07jwzaFmjSkHwdMfKTlpCNRt9EPo+R6sUHYL5lJavRO61QTVNWoR3Vr80PBK2bpXZsmjcXFtjfqLXyXFnjrvAI/pnY2BXtgO/yE2cCEaDuBCaSw823joIZLdQoJJdTaUxLrOkrX+Xyww7SxlUcA8RFuRk5BjYBHPSWU=
  app: projetlpa2111
  on:
    repo: yaman0/projet_LPA2
  run: rake db:migrate
before_script:
- psql -c 'create database db_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter format-coverage -t simplecov"
- if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
