language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: siGOCHWj3fXmVH+NkPPjSaQGUoVDM0gwRszfqQzr/Kn5Fk2uIJjAVJXTRBg2sfDbF57jBdY+EkirvbClIvbW1atv/zP4sNGUBG5uCM/XZEPz1azbYjRZMVBxMz3f9Niho+s44ECdWiY0xEUyxs+ePQpXSYSgO9tvOGGAzQVPzfder+O9r7g7j3J6uw3RwozJyjHEgnD6jPIMka2FQvZHPzFET4R3Wb7quIJqMKHa8g8pDYpTYM7d2YNvWCjv5sXEAuRoHrRRMKICL6Kb8onpreivXv2WAjYkMV+6CUSmBDTmAUMOjOwqOU8uSOKPC/5OXcDllTypTx8zzDo3JXDMC9EYqKm4qbrAI1h378MuUipcwxNykQmPZ3sdseqFOOcmT9uuWuQieADfMYLbo3qrVqXMcjO1BUXl26RoYtzXww+rOTzLHgRucCfg0JnJJ6KNuuGcCVV5S5xXfJaQe3ofVw43MrSpmg44Lto4XJ+s4CWG0KVwB6ZVKUBmYKYUT6RGYQJ/Gerh07jwzaFmjSkHwdMfKTlpCNRt9EPo+R6sUHYL5lJavRO61QTVNWoR3Vr80PBK2bpXZsmjcXFtjfqLXyXFnjrvAI/pnY2BXtgO/yE2cCEaDuBCaSw823joIZLdQoJJdTaUxLrOkrX+Xyww7SxlUcA8RFuRk5BjYBHPSWU=
  app: projetlpa2111
  on:
    repo: yaman0/projet_LPA2
  before_script:
    - psql -c 'create database db_test;' -U postgres
