default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 30
  host: localhost
  username:
  password:
  port:
  database:

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default